### ISSUE TITLE
detect version mismatch in rp-start

### ISSUE THREAD

**Issue by dbrinegar** [lightbend/sbt-reactive-app#101]
if `rp` is 1.1.0 and `rp-start` is 1.0.0 there might be key behavior breakages that are hard to identify.  If rp-start were to fail with an error message, it would make it clear that the user needs to publish an updated image

**Comment by dbrinegar** [comment]
fixed in part in lightbend/reactive-cli#137

**Comment by dbrinegar** [comment]
given the fix on Apr 26, this is low priority

**Comment by dbrinegar** [comment]
The context here is that user can be unaware that they have deployed versions of the system which are out of sync with each other, and that mis-match may cause unexpected behavior.  We're addressing it on one side, which might notice that the other side is mismatched, but to complete the loop it might be generally useful for rp-start to fail or at least warn in the event that it sees the mismatch itself, by way of helping user understand the interdependence.  This would be like the airbags to the seatbelt on the other ticket.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
