### ISSUE TITLE
conductr migration guide

### ISSUE THREAD

**Issue by alanngai** [lightbend/sbt-reactive-app#108]
need to write a  conductr migration guide from conductr to k8s and dcos.  This might be a bit tricky, since our conductr knowledge is limited.  Will likely need to get help from @edwardcallahan

**Comment by alanngai** [comment]
number of conductr users may be small enough that perhaps we can handle it case by case

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
