### ISSUE TITLE
YAML generation should be split out

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/sbt-reactive-app#110]
It would be good to split out YAML so we can debug it.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
