### ISSUE TITLE
default dockerBaseImage should be specific for reproducible builds

### ISSUE THREAD

**Issue by patrick-premont** [lightbend/sbt-reactive-app#112]
I propose that we change `dockerBaseImage` `openjdk:8-jre-alpine` to `8u171-jre-alpine3.7` to help with reproducible builds.

I have witnessed `openjdk:8-jre-alpine` going from 8u151 to 8u171, which broke an akka application that didn't have ALPN 2.0.7 (pre 10.1.x).

**Comment by dbrinegar** [comment]
version pinning is A+

issues to watch for:

* upstream removing the label we use (could be solved by copying to our own repo)
* upstream getting security fixes / upgrades that we overlook (need get notifications of upstream releases)
* giving customer final control of version they prefer

**Comment by dwijnand** [comment]
@dbrinegar do we have our own repo?

For reference, there no longer is a `8u171-jre-alpine3.7` in https://hub.docker.com/_/openjdk/, but there is `8u171-jre-alpine3.8` or `8u171-jre-alpine`.

> * giving customer final control of version they prefer

`dockerBaseImage` is always available for final control

**Comment by dbrinegar** [comment]
we're using bintray to host docker images

```
lightbend-docker-registry.bintray.io
```

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
