### ISSUE TITLE
Jstack and other debugging tools not accessible using rp-start

### ISSUE THREAD

**Issue by rbraley** [lightbend/sbt-reactive-app#118]
We are trying to attach to the running docker container and debug with jstack to see what is using the cpu so much. 
We have switched the dockerBaseImage to openjdk:8-alpine which has the jstack command
but we are running into the issue of:
1: Unable to get pid of LinuxThreads manager thread
 as documented here:
https://github.com/docker-library/openjdk/issues/76

Can we modify the rp-start script to allow for using jstack in the resultant container? 

Thanks!

**Comment by dbrinegar** [comment]
Looked into this a little and seems we have this hard coded step to "apk" install things in the base image, and the base image is also maybe hard coded.  We should in theory be able to set some other base image via the native packager and from there work out how to install the other bits we need.  We're doing something similiar for the cli build, just not for run time.

There's an option, as an example, so specify more packages to install, but they must be alpine

https://github.com/lightbend/sbt-reactive-app/blob/master/src/main/scala/com/lightbend/rp/sbtreactiveapp/SbtReactiveAppKeys.scala#L110

**Comment by rbraley** [comment]
So we modified the docker container `rp-start` script to instead of `exec "$@"` to do `nohup "$@"` followed by a long `sleep` so the container doesn't stop immediately.

Can confirm that java tools are working now, as the pid of the lagom process was 34 instead of 1. We also used the `openjdk:8-alpine` base image.

Seems to be successful. Recommend we clean this solution up into our next release. Clearly we don't want to rely on something like `sleep` long term. It would be fine to have the rp-start entrypoint use exec if it wasn't given the pid 1 of the init process. 

I believe docker has an --init parameter that might solve this as well by using tini as the init process, but we may need to do that in sbt or marathon somehow.

**Comment by longshorej** [comment]
I've used dumb-init successfully before and as a bonus it's part of Alpine's repo (meaning it would be good to add to the default `alpinePackages` value)

Changing the entry point to something like the following would work nicely (of course needing to translate to sbt)

```
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/bin/sh", "-c", "exec /rp-start \"$*\""]
```

`JAVA_OPTS` will continue to work for arguments to `java`, and any `CMD` specified will be arguments to the application's main method.

**Comment by longshorej** [comment]
Might have some time to PR this later in the week, but here's what I was thinking:

```scala
~/work/lightbend/sbt-reactive-app#dumb-init $ git diff
diff --git a/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala b/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala
index c5e8279..be4b9a4 100644
--- a/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala
+++ b/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala
@@ -393,7 +393,7 @@ case object BasicApp extends App {
       reactiveLibSecretsProject := "reactive-lib-secrets" -> true,
       reactiveLibServiceDiscoveryProject := "reactive-lib-service-discovery" -> true,
       reactiveLibStatusProject := "reactive-lib-status" -> true,
-      requiredAlpinePackages := Vector("bash"),
+      requiredAlpinePackages := Vector("bash", "dumb-init"),
       enableAkkaClusterBootstrap := false,
       enableAkkaManagement := enableAkkaClusterBootstrap.value || enableStatus.value,
       enableCommon := true,
@@ -463,7 +463,7 @@ case object BasicApp extends App {
         else
           Vector.empty),
 
-      dockerEntrypoint := (
+      dockerEntrypoint := Vector("/usr/bin/dumb-init", "--") ++ (
         if (startScriptLocation.value.isEmpty)
           dockerEntrypoint.value
         else
-> 0

```

**Comment by rbraley** [comment]
run.sh
```#!/usr/bin/env bash

bash -c "$*"```
is sufficient to fork rp-start
as 
run.sh /rp-start application

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
