### ISSUE TITLE
Request: an injection point before and after rp-start

### ISSUE THREAD

**Issue by rbraley** [lightbend/sbt-reactive-app#126]
Can we inject scripts rp-before and rp-after to debug the failure of the application in a postmortem situation without needing to alter this repo or modify the resultant docker container from a build.

**Comment by dwijnand** [comment]
@rbraley Could you describe your use case in terms of steps, problem and expectation, please?

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
