### ISSUE TITLE
Validate Settings

### ISSUE THREAD

**Issue by longshorej** [lightbend/sbt-reactive-app#13]
The plugin should validate settings to make sure they are set appropriately. For instance, it doesn't make sense to have negative memory declared.

Validate:
* Valid CPU, Memory, Disk values.
* Endpoint Name <= 15 characters long

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
