### ISSUE TITLE
stacked application.conf doesn't work in minikube

### ISSUE THREAD

**Issue by alanngai** [lightbend/sbt-reactive-app#134]
the [lightbend/es-demos repo](https://github.com/lightbend/es-demos) is a multi-project where there is a common application.conf file located in common/src/main/resources/application.conf.  Then there is the target project conf file in iotapp/src/main/resources/application.conf.  The latter should inherit and overwrite the former and the union should be used for the application.  This works as expected in 2/3 cases:

1. using `sbt iotapp/run` // works!
1. building a docker image manually and deploying onto minikube // works!  
1. building and deploy with LBO // doesn't work

[here are instructions to build and deploy whether using LBO or not](https://github.com/lightbend/es-demos/blob/master/README.md)

The crux of the problem appears to be that in the case of running with `sbt iotapp/run` or manually building and deploying the docker image, the 2 application files stack up correctly.  In the case of option 2, we see this in the k8s logs

![image](https://user-images.githubusercontent.com/1654394/43032025-60aa513e-8c62-11e8-9988-dcede03156a8.png)

However, when using LBP (sbt-reactive-app and reactive-cli), the deploy results in the following log

![image](https://user-images.githubusercontent.com/1654394/43032033-7a53a112-8c62-11e8-9c21-7f269cfbfac1.png)

which suggests that the LBO path somehow doesn't stack the application.conf files correctly.  To verify this hypothesis, I simply copied everything from common/src/main/resources/application.conf to iotapp/src/main/resources/application.conf and then cleared out the former.  When I did this, the application deployed correctly.  [Here's a comparison](https://github.com/lightbend/es-demos/compare/bug/issue-134-broken/alan...bug/issue-134-workaround/alan) to show the difference.

**Comment by dwijnand** [comment]
@alanngai could you document the working "building a docker image manually and deploying onto minikube" steps and the non-working "building and deploy with LBO", please?

**Comment by alanngai** [comment]
I'd need to dig into the history of the es-demos to get the exact config back then.  Even so, I don't think it was a very standard way of sharing configs between sub-projects.  Probably not worthwhile doing at this point.  I'm going to close this ticket
