### ISSUE TITLE
Invalid protocol in HttpEndpoint

### ISSUE THREAD

**Issue by ignasi35** [lightbend/sbt-reactive-app#142]
In [`HttpEndpoint`](https://github.com/lightbend/sbt-reactive-app/blob/eb8f3a788e6eba37afd09000b9c83f667ea2d008/src/main/scala/com/lightbend/rp/sbtreactiveapp/Endpoint.scala#L30) the protocol `http` is used. IIUC the protocol field should only use values `tcp` or `udp` and values like `cql`, `broker`, `http` or `https` should be used as port names instead.

I may be off by a mile, though, and confusing the meaning of the field `protocol` in `Endpoint` with that in `SRV` records (https://en.wikipedia.org/wiki/SRV_record#Record_format).

**Comment by TimMoore** [comment]
I think this is actually OK, if a bit confusing. This value doesn't map directly to the `protocol` used to define the Kubernetes service protocol. That mapping happens here: https://github.com/lightbend/reactive-cli/blob/5f720eb5a8a5d63962ffc5b6f2c3c1a27c8a54ac/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/Service.scala#L31
