### ISSUE TITLE
Support openjdk18-openshift as base image

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/sbt-reactive-app#147]
Currently some stuff is hardcoded to Alpine.
We should allow openjdk18-openshift as the base image if someone wants to use that.

1.4.0 for example defines `requiredAlpinePackages` under package private. https://github.com/lightbend/sbt-reactive-app/blob/v1.4.0/src/main/scala/com/lightbend/rp/sbtreactiveapp/SbtReactiveAppKeys.scala#L312-L316

```scala
  /**
   * Defines alpine packages that are installed (and required) by this plugin. This is combined with the user-defined
   * packages (`alpinePackages`).
   */
  private[sbtreactiveapp] val requiredAlpinePackages = SettingKey[Seq[String]]("rp-required-alpine-packages")
```

This is set to `Seq("bash")`, and then generates `RUN /sbin/apk add --no-cache bash`.

As a workaround I am defining the following in build.sbt:

```scala
val rpRequiredAlpinePackages = settingKey[Seq[String]]("")
```

**Comment by cunei** [comment]
I just submitted a pull request that enables the use of arbitrary docker base images, based on either apk, deb, or rpm. It is now possible to specify, for example:
```
  .settings(dockerBaseImage := "fedora:latest", packagingFormat := "dnf", userPackages := Seq("java-1.8.0-openjdk"))
```
or
```
  .settings(dockerBaseImage := "openjdk:8-jre-slim", packagingFormat := "apt-get")
```
