### ISSUE TITLE
application.conf from dependencies not being merged in rp-application.conf

### ISSUE THREAD

**Issue by renatocaval** [lightbend/sbt-reactive-app#148]
It seems that there is a bug when merging `application.conf` files in `rp-application.conf`.

From the docs we read: 

https://github.com/lightbend/sbt-reactive-app/blob/4d2348edadf0d4f49675ab25e0214a35c85c690d/src/main/scala/com/lightbend/rp/sbtreactiveapp/SbtReactiveAppKeys.scala#L262-L267

I'm not sure about what is being referenced as 'dependencies'. I guess any project dependency, not jar dependencies.

My understanding is that if `hello-impl` has a `.dependsOn(hello-api)` and `hello-api` has an `application.conf` file, then that `application.conf` file should be merged into the `rp-application.conf` produced by `hello-impl`. 
Is that correct?

You can reproduce it using the following project:
https://github.com/renatocaval/hello-lagom-scala-rp

**Comment by renatocaval** [comment]
I believe I found where in the code this is being processed and why it's not picking the file.

Here, we read the value of `rpPrependRpConf` and pass it to an `extractApplicationConf` method.

https://github.com/lightbend/sbt-reactive-app/blob/d285cbae42405666bfa67ecfecefc53359cb0347/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L278-L290

later on, inside `extractApplicationConf` method

https://github.com/lightbend/sbt-reactive-app/blob/d13356b73881d54a93b89edb1cc589b9a7fa4827/src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Build.scala#L33-L47

we lookup only the files in `unmanagedResources`, but not in the classpath. 

This confirms that:
1. we don't include `application.conf` from jar file (I guess that's good)
2. we only include files from the current project, not from dependent projects.

**Comment by renatocaval** [comment]
Some more info after further investigations:

Typesafe config loads first all `reference.conf` files and then all `application.conf` files.

However, if you pass the config explicitly, like in `-Dconfig.resource=rp-application.conf`, it won't load any `application.conf`, only `reference.conf` files. 

We don't need to name it `rp-application.conf`, but we do need to generate a file and pass it to the process using `-D`, but as a consequence we don't load any other `application.conf` and therefore the application may behave differently in dev and prod environments. 

In dev mode, all `application.conf` files are loaded. In prod mode, only the one in defined by the app itself will be loaded because it's copied into `rp-application.conf`.

I don't think we should scan the classpath and merge all `application.conf` we find into `rp-application.conf` file.

**Comment by TimMoore** [comment]
@renatocaval could we replace the explicit inclusion of `application.conf` into `rp-application.conf` with a HOCON `include "application.conf"` statement?

https://github.com/lightbend/config/blob/master/HOCON.md#includes

I believe this would include _all_ `application.conf` resources found in the classpath, using the same runtime mechanism that is used to load the file ordinarily. I think it would simplify this sbt plugin and also have more consistent behavior.

**Comment by renatocaval** [comment]
Sorry @TimMoore, somehow I missed your last message. 

Yes, this could be a solution indeed.

**Comment by cunei** [comment]
I looked into this issue. The file `rp-application.conf` is built using the value of the `dependencyClasspath` and the list of the `unmanagedResources` of the current sbt subproject. The `dependencyClasspath` includes all of the jars that are in the resolved classpath, including the `libraryDependencies`, their dependencies, and the target class directories of the other dependent sbt subprojects, and their dependencies.

The component that points to the target class directory of the dependent subprojects looks like `.../target/scala-2.12/classes`, and obviously does not contain the unmanaged resources that would be packaged in the final jar. In order to minimize changes, I prepared a pull request that extracts the list of transitively dependent sbt subprojects, and finds the unmanaged resources of all of them, adding those to the `rp-application.conf`. The pull request is at: https://github.com/lightbend/sbt-reactive-app/pull/156

This is an example:
```
$ cat build.sbt
val a=project.enablePlugins(SbtReactiveAppPlugin)
val b=project.enablePlugins(SbtReactiveAppPlugin).settings(
  libraryDependencies += "com.lightbend.rp" % "reactive-lib-akka-management_2.12" % "0.7.0"
).dependsOn(a)
val c=project.enablePlugins(SbtReactiveAppPlugin).dependsOn(b)
$ cat ./a/src/main/resources/application.conf
aaa: 11
$ cat ./b/src/main/resources/application.conf
bbb: 22
$ cat ./c/src/main/resources/application.conf
ccc: 33
```
Produces:
```
$ cat ./c/target/scala-2.12/resource_managed/main/sbt-reactive-app/rp-application.conf
# Generated by sbt-reactive-app. To disable this, set the `prependRpConf` SBT key to `""`.

# jar:file:/home/cunei/.ivy2/cache/com.lightbend.rp/reactive-lib-akka-management_2.12/jars/reactive-lib-akka-management_2.12-0.7.0.jar!/rp-tooling.conf

akka {
  library-extensions += "com.lightbend.rp.akkamanagement.AkkaManagementAutostart"

  management {
    http {
      hostname = ${?RP_ENDPOINT_AKKA_MGMT_HTTP_HOST}
      port = ${?RP_ENDPOINT_AKKA_MGMT_HTTP_PORT}
      bind-hostname = ${?RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_HOST}
      bind-port = ${?RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_PORT}
    }
  }
}
# file:/home/cunei/activities/test-vari/sbt-reactive-app-test/a/src/main/resources/application.conf

aaa: 11

# file:/home/cunei/activities/test-vari/sbt-reactive-app-test/c/src/main/resources/application.conf

ccc: 33

# file:/home/cunei/activities/test-vari/sbt-reactive-app-test/b/src/main/resources/application.conf

bbb: 22
```
This `rp-application.conf` for project `c` includes both the `application.conf` found in a jar that is a dependency of project `b`, as well as the unmanaged `application.conf` files of both projects `a` and `b`, transitive dependencies of `c`.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/lightbend/sbt-reactive-app/pull/156
