### ISSUE TITLE
Use the new Lightbend helm-charts repo

### ISSUE THREAD

**Issue by marcoderama** [lightbend/sbt-reactive-app#160]
The default location for the Lightbend helm-charts repo has moved to https://repo.lightbend.com/helm-charts and the old location (https://lightbend.github.io/helm-charts) is deprecated (and may go away at some point).  sb-reactive-app should use the new location.

**Comment by marcoderama** [comment]
Suggested fix in PR https://github.com/lightbend/sbt-reactive-app/pull/159

**Comment by marcoderama** [comment]
Hey @TimMoore, does this need to be in backlog given that I provide the fix in PR 
https://github.com/lightbend/sbt-reactive-app/pull/159?

**Comment by TimMoore** [comment]
Thanks for pointing that out @marcoderama. Moved to "review".
