### ISSUE TITLE
bug: dockerEntrypoint is overridden to be empty

### ISSUE THREAD

**Issue by adarshaj** [lightbend/sbt-reactive-app#161]
https://github.com/lightbend/sbt-reactive-app/commit/09ced897b9189f5c90cb5bb3318488c7b037cd65 is the culprit commit which is overriding the entrypoint to make it empty. It should instead respect the startup script location as being set couple lines above it.

In current master:
Correct lines that is setting the dockerEntrypoint: https://github.com/lightbend/sbt-reactive-app/blob/46a9eaa105fc89828188566fabbafdc35dcd42d0/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L327-L331

which is being overridden to empty right 4 lines below here:
https://github.com/lightbend/sbt-reactive-app/blob/46a9eaa105fc89828188566fabbafdc35dcd42d0/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L335

**Comment by TimMoore** [comment]
Thanks, @adarshaj! Would you be able to send a pull request?

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
