### ISSUE TITLE
async-dns incompatibility under Akka (2.5.14+)

### ISSUE THREAD

**Issue by thomschke** [lightbend/sbt-reactive-app#163]
Please update to reactive-lib v0.9.3 due to lightbend/reactive-lib#93.

**Comment by thomschke** [comment]
https://github.com/lightbend/sbt-reactive-app/blob/b077ef8d55ce37c24deabe5b417a3b56d3fa4153/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L33

**Comment by eed3si9n** [comment]
I am planning to make a new release of reactive-lib and sbt-reactive-app soon.

**Comment by eed3si9n** [comment]
This was fixed in 1.6.0 - https://developer.lightbend.com/blog/2019-01-09-orchestration-1-6-0/
