### ISSUE TITLE
Simple projects produce empty rp-application.conf

### ISSUE THREAD

**Issue by ignasi35** [lightbend/sbt-reactive-app#171]
Projects that don't require any managed config will get an `rp-application.conf` that's empty instead of containing at least `include "application.conf"`. When `rp-application.conf` all the contents of `applicaiton.conf` are ignored.

See https://github.com/lightbend/sbt-reactive-app/blob/master/src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Build.scala#L49

### Steps to reproduce

Create a simple Play app. Add `sbt-reactive-app` and publish. By default no `reactive-lib` module is enabled which causes `rp-application.conf` to be empty. 

### Workaround 

The workaround is to manually add a dependency to just any artifact in `"com.lightbend.rp" %% "reactive-lib-xxx" % "1.6.0"`.

**Comment by eed3si9n** [comment]
I should've fixed this before releasing 1.7.0.
