### ISSUE TITLE
Play application containerized with version 1.7.0 does not start

### ISSUE THREAD

**Issue by olivierlemasle** [lightbend/sbt-reactive-app#177]
Latest version (1.7.0) does not work for Play Framework projects, because Play has no permission to write the PID in `/opt/docker/RUNNING_PID`.

To reproduce the bug, simply follow the steps in https://developer.lightbend.com/docs/lightbend-orchestration/current/getting-started/sbt-play-minikube.html (with `rp` 1.7.0 installed).

Deployment succeeds, however accessing the server gives an error "502 Bad Gateway" and the pod has these logs:

```
Oops, cannot start the server.
java.nio.file.AccessDeniedException: /opt/docker/RUNNING_PID
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:159)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:49)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

Creating the image with `docker:publishLocal` and running it manually gives the same error.

I suppose it may be related to https://github.com/sbt/sbt-native-packager/issues/1198 or to the recent changes on Docker image building.

**Comment by eed3si9n** [comment]
Which version of reactive-cli are you using? rp 1.7.0 should put `-Dplay.server.pidfile.path=/dev/null` to workaround this - https://github.com/lightbend/reactive-cli/pull/197
You can also put the following in build.sbt to make the working directory writable:

```scala
import com.typesafe.sbt.packager.docker.DockerChmodType
dockerChmodType := DockerChmodType.UserGroupWriteExecute
```

**Comment by olivierlemasle** [comment]
@eed3si9n Using reactive-cli 1.7.0:

    $ rp version
    rp (Reactive CLI) 1.7.0
    jq support: Available

As I wrote in the original message, you can reproduce the issue with the simple steps of https://developer.lightbend.com/docs/lightbend-orchestration/current/getting-started/sbt-play-minikube.html.

In this case, lightbend/reactive-cli#197 does not fix the issue because `AkkaClusterBootstrapping` is not enabled, so `-Dplay.server.pidfile.path=/dev/null` [is not added](https://github.com/eed3si9n/reactive-cli/blob/2468511ab96e9b35441692b02d60758e9c67bb04/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/PodTemplate.scala#L92).

I've also tried your workaround (using `DockerChmodType.UserGroupWriteExecute`) but it does not seem to work. I suppose it's https://github.com/sbt/sbt-native-packager/issues/1198: 

When I log into the container:

    bash-4.4$ whoami 
    whoami: unknown uid 1001

**Comment by eed3si9n** [comment]
Hopefully this is now fixed with updates to rp (https://github.com/lightbend/reactive-cli/pull/201) and sbt-reactive-app.
