### ISSUE TITLE
Upgrade from Play v 2.6.5 to 2.7.3 (same Akka v2.5.3)

### ISSUE THREAD

**Issue by helena** [lightbend/sbt-reactive-app#187]
`sbt-reactive-app` v1.7.3 uses Play [v2.6.5](https://github.com/lightbend/sbt-reactive-app/blob/v1.7.3/build.sbt#L8)

Play 2.6.5 uses akka 2.5.23, but so does [v2.7.3](https://github.com/playframework/playframework/releases/tag/2.7.3). An upgrade may be helpful even though this is set to EOL in ~8 months.

**Comment by ihostage** [comment]
@helena Lightbend Orchestration is deprecated. 🤷‍♂ See README.
> Lightbend Orchestration is no longer actively developed and will reach its End of Life on April 15, 2020.
>
> We recommend Migrating to the Improved Kubernetes Deployment Experience.

**Comment by TimMoore** [comment]
@helena that dependency is on [Play JSON](https://github.com/playframework/play-json), which is a separate project from Play Framework (which depends on Play JSON itself). There are more recent versions of Play JSON than 2.6.5, but I'm not sure about the backward compatibility situation. Is there a specific reason to update?

**Comment by TimMoore** [comment]
BTW Play JSON doesn't depend on Akka directly

**Comment by helena** [comment]
Possible user issue I was looking into. Thanks @TimMoore. I did previously see the EOL in ~8 months, for some dependency issue in someone's build this came up. I'll close because the JSON is different, I was solely looking at their play and its version.

**Comment by TimMoore** [comment]
OK I think that's unrelated, so I'll close this until/unless we get more information about whether Play JSON is causing the problem.
