### ISSUE TITLE
Add Akka DNS Resolver only when required feature is enabled

### ISSUE THREAD

**Issue by fsat** [lightbend/sbt-reactive-app#27]
Akka DNS Resolver is required if service discovery feature or clustering feature is enabled.

The correct way to do this is enable service discovery feature if clustering feature is enabled. However, this can't be done because enable clustering is a SBT Task while service discovery feature is a SBT Setting.

SBT doesn't allow assigning Setting value from the Task, hence I'm raising this issue.

**Comment by longshorej** [comment]
It's a shaded dependency - I think the build just needs to be modified, perhaps I need to mark the dependency as `provided` since we're including it in the assembly JARs. We shouldn't have to add the resolver to the user's project.

**Comment by longshorej** [comment]
This is fixed - see these PRs:

https://github.com/lightbend/sbt-reactive-app/pull/57
https://github.com/lightbend/reactive-lib/pull/47 and
