### ISSUE TITLE
scripted test for rp-tooling.conf behavior

### ISSUE THREAD

**Issue by longshorej** [lightbend/sbt-reactive-app#34]
Need to test the behavior that will be/was merged in #33

**Comment by mitkus** [comment]
Akka, Lagom and Play use application.conf files for keeping all kinds of configuration settings. It is often useful to swap out application.conf and leave the code unchanged for running in different environments eg. dev and prod.

sbt-reactive-app build plugin has `prependRpConf` setting that allows adding some configuration to an existing project configuration at build time. This feature is not covered by tests so far.

The task is to write a scripted integration test for `prependRpConf`, following example of other tests in  `src/sbt-test/sbt-reactive-app/`.

Useful docs: https://www.scala-sbt.org/1.0/docs/Testing-sbt-plugins.html
