### ISSUE TITLE
Expose SBT settings to appropriately size JVMs and Containers

### ISSUE THREAD

**Issue by longmuir** [lightbend/sbt-reactive-app#69]
This would be a nice to have. Appropriately sizing JVMs is a big challenge that our customers have. Container limits (cgroups, Kubernetes resource limits) add another layer to the mix and complicate things further. While determining appropriate values requires measuring individual applications, exposing SBT settings to appropriately these values would help avoid the cases where container limits and JVM sizing are out of sync - which could result in JVMs crashing/restarting without warning.

This might take the form of exposing SBT settings for Kubernetes Resource Requests and Limits, and to set a value for the JVM parameter:
-XX:MaxRAMFraction=<float>

Potential limitation: The XX:MaxRAMFraction and UseCGroupMemoryLimitForHeap settings are only available as of JDK 8u131. This should be documented with these settings.

Related Blog posts:
https://very-serio.us/2017/12/05/running-jvms-in-kubernetes/
https://blog.csanchez.org/2017/05/31/running-a-jvm-in-a-container-without-getting-killed/

**Comment by ihostage** [comment]
Hi! Someone already started to implement this issue? 😄 And this issue correlates with `SbtReactiveAppKeys#memory` setting?

**Comment by ihostage** [comment]
I setted next settings for my Lagom service:
```
.settings(dockerBaseImage := "openjdk:8u171-jre-alpine") // >= 8u131
.settings(javaOptions in Universal ++= Seq(
      "-J-XX:+UnlockExperimentalVMOptions",
      "-J-XX:+UseCGroupMemoryLimitForHeap",
      "-J-XX:MaxRAMFraction=1",
      "-J-XshowSettings:vm"
))
.settings(memory := 512*1024*1024) // 512m
```
and VM settings of service (running on K8S):
```
VM settings:
    Max. Heap Size (Estimated): 455.50M
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM
```

@longmuir You wanted this?

**Comment by ihostage** [comment]
Moreover, I found this code:
https://github.com/lightbend/sbt-reactive-app/blob/f76a97679e558492a57e79cbb459b60cd2306d54/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L491-L495
And now I can use only `memory` settings.
```
.settings(dockerBaseImage := "openjdk:8u171-jre-alpine")
.settings(memory := 512*1024*1024) // 512m
.settings(javaOptions in Universal ++= Seq("-J-XshowSettings:vm"))
..................
VM settings:
    Max. Heap Size (Estimated): 114.00M
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM
```
Or set custom value of `MaxRAMFraction`:
```
.settings(dockerBaseImage := "openjdk:8u171-jre-alpine")
.settings(memory := 512*1024*1024) // 512m
.settings(javaOptions in Universal ++= Seq(
  "-J-XX:MaxRAMFraction=1",
  "-J-XshowSettings:vm"
))
..................
VM settings:
    Max. Heap Size (Estimated): 455.50M
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM
```

**Comment by ihostage** [comment]
Andrius @mitkus maybe close this issue? 😄

**Comment by eed3si9n** [comment]
@ihostage Thanks for the comments. It seems like we do have those feature, so I am closing this issue.
