### ISSUE TITLE
deploy doesn't work on Windows

### ISSUE THREAD

**Issue by longshorej** [lightbend/sbt-reactive-app#80]
The deploy support in https://github.com/lightbend/sbt-reactive-app/pull/77 hasn't been fully implemented for Windows.

It's quite close, but forking a process with spaces in the arguments breaks the nodejs libs on Windows. We'll need to spend some time to investigate a fix.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
