### ISSUE TITLE
YAML parser / renderer

### ISSUE THREAD

**Issue by longshorej** [lightbend/sbt-reactive-app#90]
This issue tracks what could be improved with a proper YAML library (not available for scala native yet)

* More robust output, removing hand-rolled json->yaml conversion
* Parsing of `minikube addons list`

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
