### ISSUE TITLE
deploy minikube to guide user for reactive sandbox failures

### ISSUE THREAD

**Issue by longshorej** [lightbend/sbt-reactive-app#91]
If reactive-sandbox fails to start, we should tell the user what commands they can use to inspect why.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
