### ISSUE TITLE
Integrate reactive-cli yaml generation

### ISSUE THREAD

**Issue by patrick-premont** [lightbend/sbt-reactive-app#92]
It would be nice if the plugin could take care of running the reactive-cli to generate the Kubernetes yaml files from the docker image it produces.

Without this, it is difficult to automate the generation of a Kubernetes yaml files that use a digest-based docker image reference (the `@` syntax, instead of tags using the `:` syntax).

This is the syntax I would need in my yaml files, so in this case, the feature would be dependent on the completion of https://github.com/lightbend/reactive-cli/issues/122.

**Comment by alanngai** [comment]
this likely requires us to re-think a big part of our tool chain, which I'm not opposed to, but would affect how soon we could get to it

**Comment by guizmaii** [comment]
Why not just another sbt plugin above the `rp` command line ? 

It's a thing I'm right now working on. Will open source its initial version today.

**Comment by guizmaii** [comment]
I just open-sourced my project: https://github.com/Colisweb/sbt-rp

It's still work in progress. I'm blocked by a problem explained here: https://discuss.lightbend.com/t/reactive-cli-lagom-sbt-sbt-plugin-trigger-a-task-when-all-the-sub-projects-have-finished-a-task/1394

**Comment by dwijnand** [comment]
The other option is to publish a part of reactive-cli's logic as a library that this (and maven's) plugin can re-use. Aka https://github.com/lightbend/reactive-cli/issues/93.

**Comment by patrick-premont** [comment]
A library is indeed preferable, as it would remove the cli as a dependency of the build, with all the version management it entails on all team member's computers and within CI build agents.

A challenge would be to preserve `jq` functionality. Perhaps https://github.com/arakelian/java-jq could be useful.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
