### ISSUE TITLE
 "deploy minikube" support for "--skip-refresh" option

### ISSUE THREAD

**Issue by erip** [lightbend/sbt-reactive-app#97]
I'm trying to issue `sbt "deploy minikube"` behind a proxy. Normally, I might use `--skip-refresh` so the cache isn't refreshed to avoid a build failure.

I can't seem to do this by passing the arg normally: `sbt "deploy minikube --skip-refresh"` and I can't seem to find anything in the docs about additional args.

Is this supported? If yes and it's documented, it might be worth making it easier to find. If yes and it's undocumented, I would love to help write up some docs.

If it's unsupported, 😭

**Comment by longshorej** [comment]
Hi @erip - hrm, not currently supported. We could add a `SettingKey` to allow arbitrary arguments to be added to the `helm` invocation, you could then set it on a per-project basis. Would that work?

cc @dbrinegar

**Comment by erip** [comment]
I suspect it might, but it runs the risk of making the number of possible flags huge. If there were some way to specify insecure registries, pass in a proxy address, or similar, that might be easier... 

Thanks for the great tool and for being receptive to our needs -- you all are doing amazing work.

**Comment by erip** [comment]
I might be misread this, but is [this](https://github.com/lightbend/sbt-reactive-app/blob/master/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L192) not passing args to the helm invocation? If not, this is probably the entrypoint for doing such a thing, right?

**Comment by dbrinegar** [comment]
I think the helm steps you want to modify are here https://github.com/lightbend/sbt-reactive-app/blob/master/src/main/scala/com/lightbend/rp/sbtreactiveapp/cmd/helm.scala#L28

The thing you're seeing above is for a running a custom helm task via sbt, which would use whatever args you provide as shown.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
